#======== World=================
/gate/world/geometry/setXLength 400.0 mm
/gate/world/geometry/setYLength 400.0 mm
/gate/world/geometry/setZLength 400.0 mm
/gate/world/setMaterial Air

#======Boundary Box =====================
/gate/world/daughters/name                    BB
/gate/world/daughters/insert                  box
#/gate/BB/placement/setTranslation          10.0 10.0 10.0 mm
/gate/BB/placement/setTranslation          0.0 0.0 0.0 mm
/gate/BB/geometry/setXLength                10.0 cm
/gate/BB/geometry/setYLength                10.0 cm
/gate/BB/geometry/setZLength                200.0 mm
/gate/BB/setMaterial             Air
/gate/BB/vis/setVisible 1
/gate/BB/vis/setColor             red

#===================PLANE1 =======================
/gate/BB/daughters/name                    scatterer
/gate/BB/daughters/insert           box
/gate/scatterer/placement/setTranslation 0.0 0.0 9.5 cm
/gate/scatterer/geometry/setXLength                1.72 cm
/gate/scatterer/geometry/setYLength                1.72 cm
/gate/scatterer/geometry/setZLength                0.25 cm
/gate/scatterer/setMaterial             CdTe

#=========================PLANE2 (centre at global system)=============================================================================
/gate/BB/daughters/name                    absorber
/gate/BB/daughters/insert           box
/gate/absorber/placement/setTranslation 0.0 0.0 9.75 cm
/gate/absorber/geometry/setXLength                1.72 cm
/gate/absorber/geometry/setYLength                1.72 cm
/gate/absorber/geometry/setZLength                0.25 cm
/gate/absorber/setMaterial             CdTe