################################################################################################
# The GEOMETRY of your system that is needed to identify  the layers using the volumeID of the hits
################################################################################################
/gate/geometry/setMaterialDatabase data/GateMaterials.db
/control/execute mac/geometry.mac

################################################################################################
# Your options for the DIGITIZATION. An example with an adder and an energy blurring
################################################################################################
/gate/digitizer/layers/insert clustering
/gate/digitizer/layers/clustering/setAcceptedDistance 3 mm
/gate/digitizer/layers/clustering/setRejectionMultipleClusters 0
/gate/digitizer/layers/insert adder

/gate/digitizer/layers/insert localBlurring
/gate/digitizer/layers/localBlurring/chooseNewVolume scatterer
/gate/digitizer/layers/localBlurring/scatterer/setResolution 0.12
/gate/digitizer/layers/localBlurring/scatterer/setEnergyOfReference 511 keV
/gate/digitizer/layers/localBlurring/chooseNewVolume absorber
/gate/digitizer/layers/localBlurring/absorber/setResolution 0.14
/gate/digitizer/layers/localBlurring/absorber/setEnergyOfReference 511 keV
/gate/digitizer/layers/insert sp3Dlocalblurring
/gate/digitizer/layers/sp3Dlocalblurring/chooseNewVolume scatterer
/gate/digitizer/layers/sp3Dlocalblurring/scatterer/setSigma 1.5 1.5 0.0 mm
/gate/digitizer/layers/sp3Dlocalblurring/chooseNewVolume absorber
/gate/digitizer/layers/sp3Dlocalblurring/absorber/setSigma 2.0 2.0 0.0 mm
/gate/digitizer/layers/insert DoImodel
/gate/digitizer/layers/DoImodel/setAxis 0 0 1
/gate/digitizer/layers/DoImodel/setDoIModel DoIBlurrNegExp
/gate/digitizer/layers/DoImodel/DoIBlurrNegExp/setExpInvDecayConst -2.85144 mm
/gate/digitizer/layers/DoImodel/DoIBlurrNegExp/setCrysEntranceFWHM 8 mm

/gate/digitizer/layers/insert energyThresholder
/gate/digitizer/layers/energyThresholder/setThreshold 85 keV

################################################################################################
# INITIALIZE is needed to recover volumeID from hits using DetectorConstruction
################################################################################################
/gate/run/initialize