# Type can be Surface or Volume

#/gate/source/addSource sphere1
#/gate/source/sphere1/gps/pos/type {type}
#/gate/source/sphere1/gps/pos/shape Sphere
#/gate/source/sphere1/gps/pos/radius 3 mm
#/gate/source/sphere1/gps/particle gamma
#/gate/source/sphere1/gps/ene/type Mono
#/gate/source/sphere1/gps/ene/mono {energy_keV} keV
#/gate/source/sphere1/setActivity 1 MBq
#/gate/source/sphere1/gps/ang/type iso
#/gate/source/sphere1/gps/pos/centre 5 0 -5 mm

/gate/source/addSource parallelepiped1
/gate/source/parallelepiped1/gps/pos/type {type}
/gate/source/parallelepiped1/gps/pos/shape Para
/gate/source/parallelepiped1/gps/pos/halfx 3 mm
/gate/source/parallelepiped1/gps/pos/halfy 3 mm
/gate/source/parallelepiped1/gps/pos/halfz 3 mm
/gate/source/parallelepiped1/gps/particle gamma
/gate/source/parallelepiped1/gps/ene/type Mono
/gate/source/parallelepiped1/gps/ene/mono {energy_keV} keV
/gate/source/parallelepiped1/setActivity 1 MBq
/gate/source/parallelepiped1/gps/ang/type iso
/gate/source/parallelepiped1/gps/pos/centre 0 0 0 mm

#/gate/source/addSource sphere2
#/gate/source/sphere2/gps/pos/type {type}
#/gate/source/sphere2/gps/pos/shape Sphere
#/gate/source/sphere2/gps/pos/radius 1 mm
#/gate/source/sphere2/gps/particle gamma
#/gate/source/sphere2/gps/ene/type Mono
#/gate/source/sphere2/gps/ene/mono 250 keV
#/gate/source/sphere2/setActivity 1 MBq
#/gate/source/sphere2/gps/ang/type iso
#/gate/source/sphere2/gps/pos/centre 5 -5 -5 mm
#
#/gate/source/addSource parallelepiped2
#/gate/source/parallelepiped2/gps/pos/type {type}
#/gate/source/parallelepiped2/gps/pos/shape Para
#/gate/source/parallelepiped2/gps/pos/halfx 1 mm
#/gate/source/parallelepiped2/gps/pos/halfy 1 mm
#/gate/source/parallelepiped2/gps/pos/halfz 1 mm
#/gate/source/parallelepiped2/gps/particle gamma
#/gate/source/parallelepiped2/gps/ene/type Mono
#/gate/source/parallelepiped2/gps/ene/mono 250 keV
#/gate/source/parallelepiped2/setActivity 1 MBq
#/gate/source/parallelepiped2/gps/ang/type iso
#/gate/source/parallelepiped2/gps/pos/centre -5 -5 -5 mm