/vis/open                     OGLIQt
/vis/drawVolume
/vis/viewer/zoom 1.5
/vis/viewer/set/viewpointThetaPhi -110 -30
#/tracking/storeTrajectory     0

/vis/scene/add/trajectories
/vis/scene/endOfEventAction   accumulate -1
/vis/scene/add/axes            0 0 0 50 mm
/vis/scene/add/text            10 0 0 mm  20 0 0   X
/vis/scene/add/text            0 10 0 mm  20 0 0   Y
/vis/scene/add/text            0 0 10 mm  20 0 0   Z

/gate/scatterer/vis/setVisible 1
/gate/scatterer/vis/setColor             green
/gate/absorber/vis/setVisible 1
/gate/absorber/vis/setColor             blue




/vis/open                     OGLIQt
/vis/drawVolume
/vis/viewer/zoom 1.5
/vis/viewer/set/viewpointThetaPhi -110 -30
/tracking/storeTrajectory     1
/vis/scene/add/trajectories
/vis/scene/add/axes            0 0 0 200 mm
/vis/scene/add/text            100 0 0 mm  20 0 0   X
/vis/scene/add/text            0 100 0 mm  20 0 0   Y
/vis/scene/add/text            0 0 100 mm  20 0 0   Z
/vis/scene/add/volume
# /vis/scene/endOfEventAction accumulate 10
#/vis/viewer/flush
#/tracking/storeTrajectory       0
#/vis/scene/add/trajectories
/vis/scene/endOfEventAction     accumulate -1
#/vis/viewer/set/auxiliaryEdge   true