/vis/open                     OGLIQt
/vis/drawVolume
/vis/viewer/zoom 1.5
/vis/viewer/set/viewpointThetaPhi -110 -30
/tracking/storeTrajectory     0

/vis/scene/add/trajectories
/vis/scene/endOfEventAction   accumulate
/vis/scene/add/axes            0 0 0 50 mm
/vis/scene/add/text            10 0 0 mm  20 0 0   X
/vis/scene/add/text            0 10 0 mm  20 0 0   Y
/vis/scene/add/text            0 0 10 mm  20 0 0   Z

/gate/scatterer/vis/setVisible 1
/gate/scatterer/vis/setColor             green
/gate/absorber/vis/setVisible 1
/gate/absorber/vis/setColor             blue