#======== World=================
/gate/world/geometry/setXLength 200 mm
/gate/world/geometry/setYLength 200 mm
/gate/world/geometry/setZLength 200 mm
/gate/world/setMaterial         Vacuum

/control/alias sensor_side 14 mm

#======Boundary Box =====================
/gate/world/daughters/name                 BB
/gate/world/daughters/insert               box
/gate/BB/placement/setTranslation          0 0 10 mm
/gate/BB/geometry/setXLength               {sensor_side}
/gate/BB/geometry/setYLength               {sensor_side}
/gate/BB/geometry/setZLength               2 mm
/gate/BB/setMaterial                       Vacuum

#==================== SCATTERER =========================
/gate/BB/daughters/name                    scatterer
/gate/BB/daughters/insert                  box
/gate/scatterer/placement/setTranslation   0 0 -0.5 mm
/gate/scatterer/geometry/setXLength        {sensor_side}
/gate/scatterer/geometry/setYLength        {sensor_side}
/gate/scatterer/geometry/setZLength        1 mm
/gate/scatterer/setMaterial                Vacuum

#================== ABSORBER =============================
/gate/BB/daughters/name                    absorber
/gate/BB/daughters/insert                  box
/gate/absorber/placement/setTranslation    0 0 0.5 mm
/gate/absorber/geometry/setXLength         {sensor_side}
/gate/absorber/geometry/setYLength         {sensor_side}
/gate/absorber/geometry/setZLength         1 mm
/gate/absorber/setMaterial                 CdTe # Silicon

# !!!!!! REMOVE THIS BLOCK IF NOT USING VOXELIZED SOURCE !!!!!!
#================== SOURCE VOLUME =============================
# This is a volume to embed the source, so that the source can be rotated
#/gate/world/daughters/name                    source_volume
#/gate/world/daughters/insert                  box
#/gate/source_volume/placement/setTranslation   0 0 0 mm
#/gate/source_volume/geometry/setXLength        250 mm
#/gate/source_volume/geometry/setYLength        400 mm
#/gate/source_volume/geometry/setZLength        250 mm
#/gate/source_volume/setMaterial                Vacuum
#/gate/source_volume/placement/setRotationAxis       1 0 0
#/gate/source_volume/placement/setRotationAngle      90 deg
#/gate/source_volume/vis/forceWireframe
#/gate/source_volume/vis/setColor red
#/gate/source_volume/vis/setVisible 1
#/gate/source_volume/vis/setDaughtersInvisible 0
