/vis/open                     OGL
/vis/drawVolume

/vis/scene/add/trajectories rich
/vis/modeling/trajectories/create/drawByParticleID #  gamma=green, e-=red
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 10
/vis/scene/add/eventID

/vis/scene/endOfEventAction   accumulate 100

/vis/viewer/zoom 5
/vis/viewer/set/viewpointThetaPhi -110 -30

/vis/scene/add/axes            0 0 0 50 mm
/vis/scene/add/text            10 0 0 mm  20 0 0   X
/vis/scene/add/text            0 10 0 mm  20 0 0   Y
/vis/scene/add/text            0 0 10 mm  20 0 0   Z

/gate/BB/vis/setVisible 0
#/gate/BB/vis/setColor             green
/gate/scatterer/vis/setVisible 1
/gate/scatterer/vis/setColor             white
/gate/sensor/vis/setVisible 1
/gate/sensor/vis/setColor             blue