######################################################################################
########################### ACTOR (2.1.2 section in paper) ###########################
######################################################################################
/gate/actor/addActor                                    SimulationStatisticActor stat
/gate/actor/stat/save                                   {out}/stats.txt
/gate/actor/addActor  ComptonCameraActor                CC_digi_BB
/gate/actor/CC_digi_BB/attachTo                         BB
/gate/actor/CC_digi_BB/save                             {out}/CC.root
/gate/actor/CC_digi_BB/saveHitsTree                     0
/gate/actor/CC_digi_BB/saveSinglesTree                  1
/gate/actor/CC_digi_BB/saveCoincidencesTree             1
/gate/actor/CC_digi_BB/saveCoincidenceChainsTree        1
/gate/actor/CC_digi_BB/saveEventInfoTree                1
/gate/actor/CC_digi_BB/absorberSDVolume                 absorber
/gate/actor/CC_digi_BB/scattererSDVolume                scatterer
/gate/actor/CC_digi_BB/numberOfTotScatterers            1
/gate/actor/CC_digi_BB/specifysourceParentID            0

######################################################################################
##################### DIGITIZER (2.1.3 section in paper) #############################
######################################################################################
# Digitizer modules can be classified into three different categories:
# - The 1st corresponds to those that spatially regroup hits to take into account the characteristics of the detector ...
# - The 2nd corresponds to modules that modify the observable values of the singles such as Depth of Interaction ...
# - The 3rd comprises those modules that filter the singles such as energy threshold modules.

# CATEGORY 1: 'singles' creation (hit regrouping)
/gate/digitizer/layers/insert adderComptPhotIdeal
#/gate/digitizer/layers/insert/rejectEvtOtherProcesses 1 TODO: does not work, why?

# CATEGORY 2: 'singles' modification

# CATEGORY 3: 'singles' filtering
#/gate/digitizer/layers/insert energyThresholder
#/gate/digitizer/layers/energyThresholder/setThreshold 0 keV

######################################################################################
####################### SORTER (2.1.4 section in paper) ##############################
######################################################################################
/gate/digitizer/Coincidences/setWindow 50. ns
/gate/digitizer/Coincidences/setAcceptancePolicy4CC keepAll # keepIfMultipleVolumeNamesInvolved

######################################################################################
################ COINCIDENCE PROCESSING (2.1.5 section in paper) #####################
######################################################################################
/gate/digitizer/name sequenceCoincidence
/gate/digitizer/insert coincidenceChain
/gate/digitizer/sequenceCoincidence/addInputName Coincidences
/gate/digitizer/sequenceCoincidence/insert sequenceRecon
/gate/digitizer/sequenceCoincidence/sequenceRecon/setSequencePolicy singlesTime # axialDist2Source
#/gate/digitizer/sequenceCoincidence/insert multiplesKiller


