# Visualization macro
#
# Usage:
# 1) In main.mac, uncomment /control/execute mac/visu.mac and reduce simulation time
# 2) Gate --qt mac/main.mac
# 3) To see source shape, type in the GUI console:
# /gate/source/source_name/visualize 1000 yellow 1

# Mandatory commands
/vis/open                     OGL
/vis/drawVolume

# Tune view point
/vis/viewer/zoom 5
/vis/viewer/set/viewpointThetaPhi -110 -30

# Show particle trajectories
/vis/scene/add/trajectories rich
/vis/modeling/trajectories/create/drawByParticleID #  gamma=green, e-=red
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 10
/vis/scene/add/eventID

/vis/scene/endOfEventAction   accumulate 100

/vis/scene/add/axes            0 0 0 50 mm
/vis/scene/add/text            10 0 0 mm  20 0 0   X
/vis/scene/add/text            0 10 0 mm  20 0 0   Y
/vis/scene/add/text            0 0 10 mm  20 0 0   Z

/gate/BB/vis/setVisible 0
#/gate/BB/vis/setColor             green
/gate/scatterer/vis/setVisible 1
/gate/scatterer/vis/setColor             white
/gate/sensor/vis/setVisible 1
/gate/sensor/vis/setColor             blue