# Usage:
# - If following block commented:
# Gate mac/main.mac -a [time,1000][out,output/time1000_cameraX5Y0Z9][posX,5][posY,0][posZ,9][seed,1]
# - If not:
# Gate mac/main.mac
#/control/alias time 100
#/control/alias out output
#/control/alis pos
#/control/alias seed 1

# ===========================
# == LOAD DATABASE         ==
# ===========================
/gate/geometry/setMaterialDatabase    ../../data/GateMaterials.db

# ===========================
# ==   GEOMETRY            ==
# ===========================
/control/execute                     mac/geometry.mac

# ===========================
# ==  PHYSICS              ==
# ===========================
/gate/physics/addPhysicsList emstandard_opt4

# =============================
# == ACTORS                  ==
# =============================
/control/execute mac/actor.mac

# ============================
# == INITIALIZE             ==
# ============================
/gate/run/initialize

# ============================
# ==  VISUALIZATION         ==
# ============================
#/control/execute                     mac/visu.mac

# ============================
# == SOURCE                 ==
# ============================
/control/execute                     mac/source.mac

# ============================
# == OUTPUT                 ==
# ============================
/gate/application/noGlobalOutput # avoids output related to PET/SPECT systems

#====================================================
#  R A N D O M   E N G I N E  A N D  S E E D
#====================================================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed} # 6781

#=====================================================
#   M E A S U R E M E N T   S E T T I N G S   
#=====================================================
/gate/application/setTimeSlice  {time} s
/gate/application/setTimeStart   0.00   s
/gate/application/setTimeStop    {time} s
/gate/application/startDAQ

exit




