/vis/open                     OGLIQt
/vis/drawVolume
/vis/viewer/zoom 1.5
/vis/viewer/set/viewpointThetaPhi -110 -30
#/tracking/storeTrajectory     0
/vis/scene/add/trajectories
/vis/scene/endOfEventAction   accumulate -1
/vis/scene/add/axes            0 0 0 10 mm

/gate/scatterer/vis/setVisible 1
/gate/scatterer/vis/setColor             green
/gate/absorber/vis/setVisible 1
/gate/absorber/vis/setColor             blue