######################################################################################
########################### ACTOR (2.1.2 section in paper) ###########################
######################################################################################
/gate/actor/addActor                                    SimulationStatisticActor stat
/gate/actor/stat/save                                   {out}/stats.txt
/gate/actor/addActor  ComptonCameraActor                CC_digi_BB
/gate/actor/CC_digi_BB/attachTo                         BB
/gate/actor/CC_digi_BB/save                             {out}/CC.root
/gate/actor/CC_digi_BB/saveHitsTree                     1
/gate/actor/CC_digi_BB/saveSinglesTree                  1
/gate/actor/CC_digi_BB/saveCoincidencesTree             1
/gate/actor/CC_digi_BB/saveCoincidenceChainsTree        1
/gate/actor/CC_digi_BB/saveEventInfoTree                1
/gate/actor/CC_digi_BB/absorberSDVolume                 absorber
/gate/actor/CC_digi_BB/scattererSDVolume                scatterer
/gate/actor/CC_digi_BB/numberOfTotScatterers            1
/gate/actor/CC_digi_BB/specifysourceParentID            0

######################################################################################
##################### DIGITIZER (2.1.3 section in paper) #############################
######################################################################################
# Digitizer modules can be classified into three different categories:
# - The 1st corresponds to those that spatially regroup hits to take into account the characteristics of the detector ...
# - The 2nd corresponds to modules that modify the observable values of the singles such as Depth of Interaction ...
# - The 3rd comprises those modules that filter the singles such as energy threshold modules.

# CATEGORY 1: 'singles' creation (hit regrouping)
# WARNING: if fluorescence is enabled (cuts <100um), there's an issue with singles (see readme)
/gate/digitizer/layers/insert adderComptPhotIdeal # WARNING: validated using livermore physics list.
/gate/digitizer/layers/adderComptPhotIdeal/verbose 2
#/gate/digitizer/layers/adderComptPhotIdeal/rejectEvtOtherProcesses 1 # IMPORTANT (TODO: fix Gate9.2 doc, wrong command)
#/gate/digitizer/layers/insert adder

# CATEGORY 2: 'singles' modification

# CATEGORY 3: 'singles' filtering
#/gate/digitizer/layers/insert energyThresholder
#/gate/digitizer/layers/energyThresholder/setThreshold 0 keV

######################################################################################
####################### SORTER (2.1.4 section in paper) ##############################
######################################################################################
# TODO: I had a case where there are valid coincident events in the Singles root tree but the Coincidences root tree is
# TODO: empty. Just increasing the simulation time or number of primaries solved the problem... Looks like the
# TODO: singles tree is not read until the end, the last few hundreds (~700) singles are not processed!
# TODO: => this can be verified using /gate/application/setTotalNumberOfPrimaries 700
/gate/digitizer/Coincidences/setWindow 50 ns
/gate/digitizer/Coincidences/setAcceptancePolicy4CC keepAll

######################################################################################
################ COINCIDENCE PROCESSING (2.1.5 section in paper) #####################
######################################################################################
/gate/digitizer/name sequenceCoincidence
/gate/digitizer/insert coincidenceChain
/gate/digitizer/sequenceCoincidence/addInputName Coincidences
/gate/digitizer/sequenceCoincidence/insert sequenceRecon
/gate/digitizer/sequenceCoincidence/sequenceRecon/setSequencePolicy singlesTime # axialDist2Source
#/gate/digitizer/sequenceCoincidence/insert multiplesKiller


